services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: carna-database
      POSTGRES_USER: carna
      POSTGRES_PASSWORD: "IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so"
    ports:
      - "5433:5432"
    networks:
      - appnet

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: carna
      DATABASE_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so
      DATABASE_NAME: "carna-database"
      JWT_SECRET: 4125442A472D4B6150645367556B58703273357638792F423F4528482B4D6251
      JWT_REFRESH_SECRET: 576E5A7134743777217A25432A462D4A614E645267556B58703273357538782F
    expose:
      - "5000"
    networks:
      - appnet
  frontend:
    container_name: frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - backend

networks:
  appnet:
    driver: bridge
