FROM node:18-alpine as build

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build && ls -la /app/dist

#---

FROM node:18-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN yarn install --production

COPY --from=build /app/dist ./dist

EXPOSE 5000

ENTRYPOINT [ "yarn", "start:prod" ]